---
- name: Configure Rsyslog File
  template: src=90-graylog.conf dest=/root/90-graylog.conf

- name: Configure Rsyslog
  shell: cat /root/90-graylog.conf > /etc/rsyslog.d/90-graylog.conf
  notify:
        - restart rsyslog
... 

