---
- include: apache.yml
- include: iphp.yml

- name: Install Epel
  yum: name=epel-release state=installed

- name: Install nagios packages
  shell: yum --enablerepo=epel -y install nagios nagios-plugins-{ping,disk,users,procs,load,swap,ssh,http}

- name: nagiosconf
  template: src=nagios dest=/root/

- name: Configure timezone
  shell: cat /root/nagios > /etc/httpd/conf.d/nagios.conf

- name: Check nagios Users
  stat: path=/etc/nagios/passwd
  ignore_errors: true
  register: nagios_user_pwfile_exists
  become: true

- name: Create empty password file
  command: touch /etc/nagios/passwd
  args:
    creates: /etc/nagios/passwd
  when: nagios_user_pwfile_exists != 0
  become: true

- name: Create nagios admin user
  command: htpasswd -b -c /etc/nagios/passwd nagiosadmin  SynTech2023
  ignore_errors: true
  when: nagios_user_pwfile_exists != 0
  become: true

- name: habilitar y ejecutar nagios
  service: name=nagios  state=restarted enabled=true

- name: habilitar y ejecutar httpd
  service: name=httpd  state=restarted enabled=true

- name: localhost
  template: src=localhost dest=/root/localhost

- name: Configure localhost
  shell: cat /root/localhost > /etc/nagios/objects/localhost.cfg

- name: Install plugin
  shell: yum --enablerepo=epel -y install nagios-plugins-ntp

- name: commands
  template: src=commands dest=/root/commands

- name: Configure commands
  shell: cat /root/commands > /etc/nagios/objects/commands.cfg

- name: nagiosserver
  template: src=nagiosserver dest=/root/nagiosserver

- name: Configure nagiosserver
  shell: cat /root/nagiosserver > /etc/nagios/nagios.cfg

- name: Crear carpeta servers
  file:
      path: /etc/nagios/servers
      state: directory
      mode: 0750

- name: chgrp
  shell: chgrp nagios /etc/nagios/servers

- name: Intall nrpe
  shell: yum --enablerepo=epel -y install nagios-plugins-nrpe

- name: node01
  template: src=node01 dest=/root/node01

- name: Configure node01
  shell: cat /root/node01 > /etc/nagios/servers/node01.cfg

- name: node02
  template: src=node02 dest=/root/node02

- name: Configure node02
  shell: cat /root/node02 > /etc/nagios/servers/node02.cfg

- name: Install windows plugin
  shell: yum --enablerepo=epel -y install nagios-plugins-nt

- name: windows
  template: src=windows dest=/root/windows

- name: Configure windows
  shell: cat /root/windows > /etc/nagios/servers/windows.cfg

- name: habilitar y ejecutar nagios
  service: name=nagios  state=started enabled=true

- name: Habilitar servicio HTTP
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Habilitar tráfico Nagios
  ansible.builtin.firewalld:
    port: 5666/tcp
    permanent: true
    state: enabled	

- name: Habilitar servicio NRPE
  ansible.posix.firewalld:
    service: nrpe
    permanent: true
    state: enabled
    immediate: true

- name: Reload firewalld
  shell: firewall-cmd --reload

- name: Install Semanage
  yum: name=policycoreutils-python state=installed

- name: Configure Semanage Nagios
  shell: semanage permissive -a nagios_unconfined_plugin_t

- name: Install nrpe client
  yum: name=nrpe state=installed

- name: Install wget
  yum: name=wget state=installed

- name: plugin memory
  shell: wget https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl

- name: Configure nrpe
  shell: echo "command[check_mem]=/usr/lib64/nagios/plugins/check_mem  -f -w 20 -c 10" >> /etc/nagios/nrpe.cfg

- name: mv mem
  shell: mv check_mem.pl /usr/lib64/nagios/plugins/check_mem

- name: chmod mem
  shell: chmod +x /usr/lib64/nagios/plugins/check_mem

- name: habilitar y ejecutar nrep
  service: name=nrpe  state=restarted enabled=true

- name: Configure selinux Mem
  shell: chcon -t nagios_unconfined_plugin_exec_t /usr/lib64/nagios/plugins/check_mem

- name: Configure selinux U Mem
  shell: chcon -u system_u -t nagios_unconfined_plugin_exec_t /usr/lib64/nagios/plugins/check_mem

- name: Configure Semanage NREP
  shell: sudo semanage permissive -a nrpe_t

...
