---
- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=/root/.my.cnf mode=0770

- name: ensure anonymous users are not in the databases
  mysql_user: name='' host=webservers password=absent

- name: remove test database
  mysql_db: name=test state=absent 
...