---
- name: Install Epel
  shell: yum install epel-release

- name: Install Utils
  shell: sudo yum --enablerepo=epel -y install nrpe nagios-plugins-{ping,disk,users,procs,load,swap,ssh}

- name: Install wget
  yum: name=wget state=installed

- name: plugin memory
  shell: wget https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl

- name: nrpe
  template: src=nrpe dest=/root/nrpe

- name: Configure nrpe
  shell: cat /root/nrpe > /etc/nagios/nrpe.cfg

- name: mv mem
  shell: mv check_mem.pl /usr/lib64/nagios/plugins/check_mem

- name: chmod mem
  shell: chmod +x /usr/lib64/nagios/plugins/check_mem

- name: habilitar y ejecutar nrep
  service: name=nrpe  state=restarted enabled=true
...