---
- name: Install Epel
  shell: yum install epel-release -y

- name: Install Utils
  shell: sudo yum --enablerepo=epel -y install nrpe nagios-plugins-{ping,disk,users,procs,load,swap,ssh}

- name: Install wget
  yum: name=wget state=installed

- name: plugin memory
  shell: wget https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl

- name: nrpe
  template: src=nrpe dest=/root/nrpe

- name: Configure nrpe
  shell: cat /root/nrpe > /etc/nagios/nrpe.cfg

- name: mv mem
  shell: mv check_mem.pl /usr/lib64/nagios/plugins/check_mem

- name: chmod mem
  shell: chmod +x /usr/lib64/nagios/plugins/check_mem

- name: habilitar y ejecutar nrep
  service: name=nrpe  state=restarted enabled=true

- name: Habilitar tráfico Nagios
  ansible.builtin.firewalld:
    port: 5666/tcp
    permanent: yes
    state: enabled

- name: Habilitar servicio NRPE
  ansible.posix.firewalld:
    service: nrpe
    permanent: true
    state: enabled
    immediate: true

- name: Install Semanage
  yum: name=policycoreutils-python state=installed

- name: Configure selinux Mem
  shell: chcon -t nagios_unconfined_plugin_exec_t /usr/lib64/nagios/plugins/check_mem

- name: Configure selinux U Mem
  shell: chcon -u system_u -t nagios_unconfined_plugin_exec_t /usr/lib64/nagios/plugins/check_mem

- name: Configure Semanage NREP
  shell: sudo semanage permissive -a nrpe_t


...