---

- name: BKPsh
  template: src=scriptBKP.sh dest=/root/
  
- name: Permisos para script
  shell: chmod +x /root/scriptBKP.sh
  
- name: Configure Cron
  shell: (crontab -l ; echo "0 2 * * * /root/scriptBKP.sh") | crontab -

...
