---
#- name: setenforce
#  shell: setenforce 0 > /dev/null 2>& 1

- name: sed
  shell: sed -i '/SELINUX/s/enforcing/disabled/' /etc/selinux/config

- name: Install Epel
  yum: name=epel-release state=installed

- name: Install php and httpd
  yum: name={{ loganalizer_packages }} state=installed
  notify: 
        - restart httpd

- name: Remove index
  shell: rm -f /var/www/html/index.php

- name: Install rsyslog-mysql
  yum: name=rsyslog-mysql state=installed

- name: Start MariaDB
  service: name=mariadb state=started enabled=true

- name: rpm
  shell: rpm -ql rsyslog-mysql.x86_64

- name: sql
  shell: mysql -u root < /usr/share/doc/rsyslog-8.24.0/mysql-createDB.sql

- name: grant 127
  shell: mysql -u root -e "grant all on Syslog.* to rsysloguser@127.0.0.1 identified by 'rsyslogpwd';"

- name: grant localhost
  shell: mysql -u root -e "grant all on Syslog.* to rsysloguser@localhost identified by 'rsyslogpwd';"

- name: flush privileges
  shell: mysql -u root -e "flush privileges;"
  
- name: rsyslog
  template: src=rsyslog dest=/root/rsyslog

- name: Configure rsyslog
  shell: cat /root/rsyslog > /etc/rsyslog.conf
  notify: 
        - restart rsyslog


- name: Download loganalizer
  ansible.builtin.get_url:
    url: http://download.adiscon.com/loganalyzer/loganalyzer-4.1.10.tar.gz
    dest: /tmp/
    mode: '0740'


- name: tar
  unarchive:
    src: /tmp/loganalyzer-4.1.10.tar.gz 
    dest: /tmp/
    extra_opts: [--strip-components=1]
    remote_src: yes

 
- name: cp loganalizer
  become: true 
  copy:
        src: /tmp/loganalyzer-4.1.10/src/
        dest: /var/www/html/log
        remote_src: yes
  

 
- name: cp contrib
  become: true 
  copy:
        src: /tmp/loganalyzer-4.1.10/contrib/*.sh
        dest: /var/www/html/log/ 
        remote_src: yes

 
- name: Chmod x
  shell: chmod +x /var/www/html/log/configure.sh secure.sh
 
- name: configure
  shell: /var/www/html/log/configure.sh

- name: secure
  shell: /var/www/html/log/secure.sh

- name: chmod
  shell: chmod 666 /var/www/html/log/config.php

- name: chown
  shell: chown -R apache.apache * 







...