---
- name: setenforce
  shel: setenforce 0

- name: sed
  shel: sed -i '/SELINUX/s/enforcing/disabled/' /etc/selinux/config

- name: Install php and httpd
  yum: name={{ loganalizer_packages }} state=installed
     notify: 
        - restart httpd

- name: Remove index
  shel: rm -f /var/www/html/index.php

- name: Install rsyslog-mysql
  yum: name=rsyslog-mysql state=installed

- name: rpm
  shel: rpm -ql rsyslog-mysql.x86_64

- name: sql
  shel: mysql -uroot -p < /usr/share/doc/rsyslog-8.24.0/mysql-createDB.sql

- name: grant 127
  shel: mysql -u root -proot -e "grant all on Syslog.* to rsysloguser@127.0.0.1 identified by 'rsyslogpwd';"

- name: grant localhost
  shel: mysql -u root -proot -e "grant all on Syslog.* to rsysloguser@localhost identified by 'rsyslogpwd';"

- name: flush privileges
  shel: mysql -u root -proot -e "flush privileges;"
  
- name: rsyslog
  template: src=rsyslog dest=/root/rsyslog

- name: Configure rsyslog
  shell: cat /root/rsyslog > /etc/rsyslog.conf
       notify: 
        - restart rsyslog

- name: wget
  get_url: url={{ http://download.adiscon.com/loganalyzer/loganalyzer-4.1.5.tar.gz }}


- name: tar
  unarchive:
    src: loganalyzer-4.1.5.tar.gz 
    dest: /root/
    extra_opts: [--strip-components=1]

 
- name: cp loganalizer
  become: true 
      copy:
        src: loganalyzer-4.1.5/src/
        dest: /var/www/html/log
  

 
- name: cp contrib
    become: true 
      copy:
        src: loganalyzer-4.1.5/contrib/*.sh
        dest: /var/www/html/log/ 

 
- name: cd
  shel: cd /var/www/html/log

 
- name: chmod
  shel: chmod  +x configure.sh secure.sh

 
- name: configure
  shel: ./configure.sh

- name: secure
  shel: ./secure.sh

- name: chmod
  shel: chmod 666 config.php

- name: chown
  shel: chown -R apache.apache * 







...