---
- name: Modifying my.cnf to be master
  template: src=config.sh dest=/root/

- name: Running sh
  shell: sh /root/config.sh
  notify:
    - restart mariadb

- name: Stop Slave
  shell: mysql -e "STOP SLAVE;"

- shell: cat "/root/p/binlog.txt"
  register: binlog

- shell: cat "/root/p/posicion.txt"
  register: posicion

- name: Grant Replication
  shell: mysql -e "CHANGE MASTER TO MASTER_HOST='192.168.50.150' , MASTER_USER='slave' , MASTER_PASSWORD='123' , MASTER_LOG_FILE='{{ binlog.stdout }}' , MASTER_LOG_POS={{ posicion.stdout }};"
  notify:
    - start slave







...